/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseños;

import java.awt.BorderLayout;
import java.awt.Color;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import diseños.Usuario_Ingresar;

/**
 *
 * @author USUARIO
 */
public class Dashboard extends javax.swing.JFrame {
int xMouse,yMouse;
    /**
     * Creates new form Principal
     */
    public Dashboard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        app_name = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_empleado = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_proveedores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_clientes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_familias = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_productos = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_detallev = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_ventas = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_principal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btncrearcuenta = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();
        encabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_cerrarsesion = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo agro.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1070, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));
        jPanel2.setLayout(null);

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        app_name.setText("AgroFacil");
        jPanel2.add(app_name);
        app_name.setBounds(40, 30, 190, 32);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(40, 70, 190, 20);

        btn_empleado.setBackground(new java.awt.Color(102, 255, 0));
        btn_empleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_empleado.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_empleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_empleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_empleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_empleadoMousePressed(evt);
            }
        });
        btn_empleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleados.png"))); // NOI18N
        btn_empleado.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Empleados");
        btn_empleado.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btn_empleado);
        btn_empleado.setBounds(0, 170, 270, 51);

        btn_proveedores.setBackground(new java.awt.Color(102, 255, 0));
        btn_proveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_proveedores.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_proveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_proveedoresMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_proveedoresMousePressed(evt);
            }
        });
        btn_proveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paquetes.png"))); // NOI18N
        btn_proveedores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Proveedores");
        btn_proveedores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btn_proveedores);
        btn_proveedores.setBounds(0, 220, 270, 51);

        btn_clientes.setBackground(new java.awt.Color(102, 255, 0));
        btn_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_clientes.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clientesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_clientesMousePressed(evt);
            }
        });
        btn_clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clasificacion.png"))); // NOI18N
        btn_clientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Clientes");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        btn_clientes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btn_clientes);
        btn_clientes.setBounds(0, 270, 270, 51);

        btn_familias.setBackground(new java.awt.Color(102, 255, 0));
        btn_familias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_familias.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_familias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_familiasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_familiasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_familiasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_familiasMousePressed(evt);
            }
        });
        btn_familias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/balas.png"))); // NOI18N
        btn_familias.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Familias");
        btn_familias.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btn_familias);
        btn_familias.setBounds(0, 320, 270, 51);

        btn_productos.setBackground(new java.awt.Color(102, 255, 0));
        btn_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_productos.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_productosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_productosMousePressed(evt);
            }
        });
        btn_productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entrega.png"))); // NOI18N
        btn_productos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Productos");
        btn_productos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btn_productos);
        btn_productos.setBounds(0, 370, 270, 51);

        btn_detallev.setBackground(new java.awt.Color(102, 255, 0));
        btn_detallev.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_detallev.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_detallev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_detallevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_detallevMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_detallevMousePressed(evt);
            }
        });
        btn_detallev.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facturas-de-papel.png"))); // NOI18N
        btn_detallev.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Detalles de Ventas");
        btn_detallev.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btn_detallev);
        btn_detallev.setBounds(0, 470, 270, 51);

        btn_ventas.setBackground(new java.awt.Color(102, 255, 0));
        btn_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ventas.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ventasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ventasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ventasMousePressed(evt);
            }
        });
        btn_ventas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bolsa-de-la-compra.png"))); // NOI18N
        btn_ventas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ventas");
        btn_ventas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btn_ventas);
        btn_ventas.setBounds(0, 420, 270, 51);

        btn_principal.setBackground(new java.awt.Color(102, 255, 0));
        btn_principal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_principal.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_principalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_principalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_principalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_principalMousePressed(evt);
            }
        });
        btn_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
        btn_principal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Principal");
        btn_principal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btn_principal);
        btn_principal.setBounds(0, 120, 270, 51);

        btncrearcuenta.setBackground(new java.awt.Color(102, 255, 0));
        btncrearcuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncrearcuenta.setPreferredSize(new java.awt.Dimension(270, 51));
        btncrearcuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncrearcuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncrearcuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncrearcuentaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncrearcuentaMousePressed(evt);
            }
        });
        btncrearcuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario.png"))); // NOI18N
        btncrearcuenta.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Crear Cuenta");
        btncrearcuenta.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel2.add(btncrearcuenta);
        btncrearcuenta.setBounds(0, 520, 270, 51);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 660));

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 500));

        encabezado.setBackground(new java.awt.Color(51, 204, 0));
        encabezado.setMaximumSize(new java.awt.Dimension(32767, 120));
        encabezado.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");
        encabezado.add(jLabel2);
        jLabel2.setBounds(140, 0, 350, 120);

        btn_cerrarsesion.setBackground(new java.awt.Color(102, 255, 0));
        btn_cerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cerrarsesion.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_cerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cerrarsesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cerrarsesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cerrarsesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cerrarsesionMousePressed(evt);
            }
        });
        btn_cerrarsesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        btn_cerrarsesion.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Cerrar Sesión");
        btn_cerrarsesion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        encabezado.add(btn_cerrarsesion);
        btn_cerrarsesion.setBounds(500, 30, 270, 51);

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo agro.png"))); // NOI18N
        encabezado.add(logo1);
        logo1.setBounds(0, 0, 130, 120);

        jPanel1.add(encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 800, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_empleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadoMouseEntered
    btn_empleado.setBackground(new Color(146,255,72));    
    }//GEN-LAST:event_btn_empleadoMouseEntered

    private void btn_empleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadoMouseExited
    btn_empleado.setBackground(new Color(102,255,0));    
    }//GEN-LAST:event_btn_empleadoMouseExited

    private void btn_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadoMousePressed
    
    }//GEN-LAST:event_btn_empleadoMousePressed

    private void btn_proveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedoresMouseEntered
    btn_proveedores.setBackground(new Color(146,255,72));    
    }//GEN-LAST:event_btn_proveedoresMouseEntered

    private void btn_proveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedoresMouseExited
    btn_proveedores.setBackground(new Color(102,255,0));    
    }//GEN-LAST:event_btn_proveedoresMouseExited

    private void btn_proveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedoresMousePressed
    
    }//GEN-LAST:event_btn_proveedoresMousePressed

    private void btn_clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMouseEntered
    btn_clientes.setBackground(new Color(146,255,72));    
    }//GEN-LAST:event_btn_clientesMouseEntered

    private void btn_clientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMouseExited
    btn_clientes.setBackground(new Color(102,255,0));    
    }//GEN-LAST:event_btn_clientesMouseExited

    private void btn_clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMousePressed
      
    }//GEN-LAST:event_btn_clientesMousePressed

    private void btn_familiasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_familiasMouseEntered
    btn_familias.setBackground(new Color(146,255,72));    
    }//GEN-LAST:event_btn_familiasMouseEntered

    private void btn_familiasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_familiasMouseExited
    btn_familias.setBackground(new Color(102,255,0));    
    }//GEN-LAST:event_btn_familiasMouseExited

    private void btn_familiasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_familiasMousePressed
      
    }//GEN-LAST:event_btn_familiasMousePressed

    private void btn_productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMouseEntered
    btn_productos.setBackground(new Color(146,255,72));    
    }//GEN-LAST:event_btn_productosMouseEntered

    private void btn_productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMouseExited
    btn_productos.setBackground(new Color(102,255,0));   
    }//GEN-LAST:event_btn_productosMouseExited

    private void btn_productosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMousePressed
        
    }//GEN-LAST:event_btn_productosMousePressed

    private void btn_detallevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detallevMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_detallevMousePressed

    private void btn_detallevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detallevMouseExited
    btn_detallev.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_btn_detallevMouseExited

    private void btn_detallevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detallevMouseEntered
    btn_detallev.setBackground(new Color(146,255,72));
    }//GEN-LAST:event_btn_detallevMouseEntered

    private void btn_ventasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ventasMouseEntered
    btn_ventas.setBackground(new Color(146,255,72));   
    }//GEN-LAST:event_btn_ventasMouseEntered

    private void btn_ventasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ventasMouseExited
    btn_ventas.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_btn_ventasMouseExited

    private void btn_ventasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ventasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ventasMousePressed

    private void btn_principalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_principalMouseEntered
    btn_principal.setBackground(new Color(146,255,72));
    }//GEN-LAST:event_btn_principalMouseEntered

    private void btn_principalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_principalMouseExited
    btn_principal.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_btn_principalMouseExited

    private void btn_principalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_principalMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_principalMousePressed

    private void btn_cerrarsesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarsesionMouseEntered
    btn_cerrarsesion.setBackground(new Color(146,255,72));
    }//GEN-LAST:event_btn_cerrarsesionMouseEntered

    private void btn_cerrarsesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarsesionMouseExited
    btn_cerrarsesion.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_btn_cerrarsesionMouseExited

    private void btn_cerrarsesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarsesionMousePressed
    
    }//GEN-LAST:event_btn_cerrarsesionMousePressed

    private void btn_cerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarsesionMouseClicked
    Usuario_Ingresar abrir = new Usuario_Ingresar();
    abrir.setVisible(true);
        
    Dashboard.this.dispose();
    }//GEN-LAST:event_btn_cerrarsesionMouseClicked

    private void btn_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMouseClicked
    Cliente_AMBM c = new Cliente_AMBM();
    c.setSize(800, 500);
    c.setLocation(0, 0);
    
    escritorio.removeAll();
    escritorio.add(c, BorderLayout.CENTER);
    escritorio.revalidate();
    escritorio.repaint();       
    }//GEN-LAST:event_btn_clientesMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
    btn_clientes.setBackground(new Color(146,255,72));    
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
    btn_clientes.setBackground(new Color(102,255,0));    
    }//GEN-LAST:event_jLabel8MouseExited

    private void btn_familiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_familiasMouseClicked
    Familia_AMBM c = new Familia_AMBM();
    c.setSize(800, 500);
    c.setLocation(0, 0);
    
    escritorio.removeAll();
    escritorio.add(c, BorderLayout.CENTER);
    escritorio.revalidate();
    escritorio.repaint();    
    }//GEN-LAST:event_btn_familiasMouseClicked

    private void btn_principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_principalMouseClicked
    escritorio.removeAll();
    }//GEN-LAST:event_btn_principalMouseClicked

    private void btn_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadoMouseClicked
    Empleado_AMBM c = new Empleado_AMBM();
    c.setSize(800, 500);
    c.setLocation(0, 0);
    
    escritorio.removeAll();
    escritorio.add(c, BorderLayout.CENTER);
    escritorio.revalidate();
    escritorio.repaint();   
    }//GEN-LAST:event_btn_empleadoMouseClicked

    private void btncrearcuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrearcuentaMouseEntered
    btncrearcuenta.setBackground(new Color(146,255,72));
    }//GEN-LAST:event_btncrearcuentaMouseEntered

    private void btncrearcuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrearcuentaMouseExited
    btncrearcuenta.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_btncrearcuentaMouseExited

    private void btncrearcuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrearcuentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncrearcuentaMousePressed

    private void btncrearcuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrearcuentaMouseClicked
    Usuario_CrearCuenta c = new Usuario_CrearCuenta();
    c.setSize(800, 500);
    c.setLocation(0, 0);
    
    escritorio.removeAll();
    escritorio.add(c, BorderLayout.CENTER);
    escritorio.revalidate();
    escritorio.repaint();   
    }//GEN-LAST:event_btncrearcuentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app_name;
    private javax.swing.JPanel btn_cerrarsesion;
    private javax.swing.JPanel btn_clientes;
    private javax.swing.JPanel btn_detallev;
    private javax.swing.JPanel btn_empleado;
    private javax.swing.JPanel btn_familias;
    private javax.swing.JPanel btn_principal;
    private javax.swing.JPanel btn_productos;
    private javax.swing.JPanel btn_proveedores;
    private javax.swing.JPanel btn_ventas;
    private javax.swing.JPanel btncrearcuenta;
    private javax.swing.JPanel encabezado;
    public static javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    // End of variables declaration//GEN-END:variables
}
